name: Meaningful Messages
favicon: null
layout_spectrum: 0.89809
typography_spectrum: 0.82028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67a4c1'
    - '#5071a4'
    - '#3f516c'
    - '#a2c0be'
    - '#cad2d4'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.7197672200854868
  rhythmicContrast: 0.25
purpose: []
